### ISSUE TITLE
Fix "UnboundLocalError: local variable 'system_message' referenced before assignment"

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/service-stats#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/service", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/service/app.py", line 139, in main
    ServiceCLI().run()
  File "/usr/local/lib/python3.7/site-packages/service/app.py", line 85, in run
    slack=self.slack,
  File "/usr/local/lib/python3.7/site-packages/service/app.py", line 122, in run
    f'\n{service_message if service_message else ""}'
UnboundLocalError: local variable 'system_message' referenced before assignment
```

**Comment by Justintime50** [comment]
v1.2.0 fixes this.
